options(repos = c(CRAN = "http://cran.rstudio.com"))
if (!require("devtools")) install.packages("devtools")
install.packages(c("httpuv", "jsonlite"))
devtools::install_github("robertzk/microserver")
microserver::run_server(list("/ping" = function(p, q) c("pong")), 3464)
